version: "1.0"
info:
  model: int-scaffold
packages:
- name: FLOW_TEST_PKG_1Project
  gitServerName: newPkg1
  gitUrl: https://github.com/PoojaAnandGit/EdgeFLOW_TEST_PKG_1
  gitUsername: PoojaAnandGit
  gitBranch: main
